services:
  postgres:
    image: postgres:16-alpine
    profiles:
      - local-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: siakad
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "3101:3001"

  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
