services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siakad
      MYSQL_USER: siakad_user
      MYSQL_PASSWORD: siakad_password
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "3101:3001"

  web:
    build: ./apps/web
    environment:
      API_INTERNAL_URL: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  mysqldata:
