-- Import once on an existing SIAKAD database to add complete student biodata.
-- Safe to run repeatedly. Existing biodata rows are updated, student rows are not deleted.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `StudentBiodata` (
  `id` VARCHAR(191) NOT NULL,
  `studentId` VARCHAR(191) NOT NULL,
  `gender` VARCHAR(50) NULL,
  `birthPlace` VARCHAR(191) NULL,
  `birthDate` DATE NULL,
  `religion` VARCHAR(100) NULL,
  `maritalStatus` VARCHAR(100) NULL,
  `nationality` VARCHAR(100) NULL,
  `nik` VARCHAR(50) NULL,
  `nisn` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `alternatePhone` VARCHAR(50) NULL,
  `email` VARCHAR(191) NULL,
  `address` VARCHAR(500) NULL,
  `rt` VARCHAR(10) NULL,
  `rw` VARCHAR(10) NULL,
  `village` VARCHAR(191) NULL,
  `district` VARCHAR(191) NULL,
  `city` VARCHAR(191) NULL,
  `province` VARCHAR(191) NULL,
  `postalCode` VARCHAR(20) NULL,
  `schoolOrigin` VARCHAR(191) NULL,
  `graduationYear` INT NULL,
  `entryYear` INT NULL,
  `entryPath` VARCHAR(100) NULL,
  `registrationNumber` VARCHAR(100) NULL,
  `bloodType` VARCHAR(5) NULL,
  `jacketSize` VARCHAR(10) NULL,
  `transportation` VARCHAR(100) NULL,
  `residenceType` VARCHAR(100) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `StudentBiodata_studentId_key` (`studentId`),
  KEY `StudentBiodata_studentId_idx` (`studentId`),
  CONSTRAINT `StudentBiodata_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `Student` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `StudentBiodata` (
  `id`, `studentId`, `gender`, `birthPlace`, `birthDate`, `religion`, `maritalStatus`, `nationality`,
  `nik`, `nisn`, `phone`, `alternatePhone`, `email`, `address`, `rt`, `rw`, `village`, `district`,
  `city`, `province`, `postalCode`, `schoolOrigin`, `graduationYear`, `entryYear`, `entryPath`,
  `registrationNumber`, `bloodType`, `jacketSize`, `transportation`, `residenceType`, `createdAt`, `updatedAt`
)
SELECT
  CONCAT('biodata_', MD5(s.`id`)),
  s.`id`,
  IF(CAST(RIGHT(s.`nim`, 1) AS UNSIGNED) % 2 = 0, 'Laki-laki', 'Perempuan'),
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 6) + 1, 'Jakarta', 'Bandung', 'Surabaya', 'Yogyakarta', 'Semarang', 'Malang'),
  DATE_ADD('2003-01-01', INTERVAL (CAST(RIGHT(s.`nim`, 4) AS UNSIGNED) % 1200) DAY),
  'Islam',
  'Belum Menikah',
  'Indonesia',
  CONCAT('33', LPAD(CAST(CAST(RIGHT(s.`nim`, 14) AS UNSIGNED) AS CHAR), 14, '0')),
  CONCAT('00', LPAD(CAST(CAST(RIGHT(s.`nim`, 10) AS UNSIGNED) AS CHAR), 10, '0')),
  CONCAT('0813', LPAD(CAST(CAST(RIGHT(s.`nim`, 8) AS UNSIGNED) AS CHAR), 8, '0')),
  CONCAT('0822', LPAD(CAST(CAST(RIGHT(s.`nim`, 8) AS UNSIGNED) AS CHAR), 8, '0')),
  COALESCE(u.`email`, CONCAT(LOWER(REPLACE(s.`nim`, ' ', '')), '@siakad.local')),
  CONCAT('Jl. Pendidikan No. ', (CAST(RIGHT(s.`nim`, 4) AS UNSIGNED) % 200) + 1),
  LPAD(CAST(((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 20) + 1) AS CHAR), 2, '0'),
  LPAD(CAST(((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 10) + 1) AS CHAR), 2, '0'),
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 5) + 1, 'Sukamaju', 'Cempaka', 'Mekarsari', 'Karangjati', 'Tegalrejo'),
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 5) + 1, 'Kecamatan Utara', 'Kecamatan Selatan', 'Kecamatan Barat', 'Kecamatan Timur', 'Kecamatan Tengah'),
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 6) + 1, 'Jakarta', 'Bandung', 'Surabaya', 'Yogyakarta', 'Semarang', 'Malang'),
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 4) + 1, 'DKI Jakarta', 'Jawa Barat', 'Jawa Tengah', 'Jawa Timur'),
  CONCAT('6', LPAD(CAST((CAST(RIGHT(s.`nim`, 4) AS UNSIGNED) % 9999) AS CHAR), 4, '0')),
  CONCAT('SMA Negeri ', (CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 20) + 1),
  CASE WHEN CAST(LEFT(s.`nim`, 4) AS UNSIGNED) >= 1900 THEN CAST(LEFT(s.`nim`, 4) AS UNSIGNED) - 1 ELSE 2025 END,
  CASE WHEN CAST(LEFT(s.`nim`, 4) AS UNSIGNED) >= 1900 THEN CAST(LEFT(s.`nim`, 4) AS UNSIGNED) ELSE 2026 END,
  ELT((CAST(RIGHT(s.`nim`, 2) AS UNSIGNED) % 4) + 1, 'Reguler', 'Transfer', 'Mandiri', 'Beasiswa'),
  CONCAT('REG-', s.`nim`),
  ELT((CAST(RIGHT(s.`nim`, 1) AS UNSIGNED) % 4) + 1, 'A', 'B', 'O', 'AB'),
  ELT((CAST(RIGHT(s.`nim`, 1) AS UNSIGNED) % 4) + 1, 'S', 'M', 'L', 'XL'),
  ELT((CAST(RIGHT(s.`nim`, 1) AS UNSIGNED) % 4) + 1, 'Sepeda Motor', 'Transportasi Umum', 'Jalan Kaki', 'Mobil Pribadi'),
  ELT((CAST(RIGHT(s.`nim`, 1) AS UNSIGNED) % 4) + 1, 'Bersama Orang Tua', 'Kos', 'Asrama', 'Kontrak'),
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3)
FROM `Student` s
LEFT JOIN `User` u ON u.`id` = s.`userId`
ON DUPLICATE KEY UPDATE
  `gender` = VALUES(`gender`),
  `birthPlace` = VALUES(`birthPlace`),
  `birthDate` = VALUES(`birthDate`),
  `religion` = VALUES(`religion`),
  `maritalStatus` = VALUES(`maritalStatus`),
  `nationality` = VALUES(`nationality`),
  `nik` = VALUES(`nik`),
  `nisn` = VALUES(`nisn`),
  `phone` = VALUES(`phone`),
  `alternatePhone` = VALUES(`alternatePhone`),
  `email` = VALUES(`email`),
  `address` = VALUES(`address`),
  `rt` = VALUES(`rt`),
  `rw` = VALUES(`rw`),
  `village` = VALUES(`village`),
  `district` = VALUES(`district`),
  `city` = VALUES(`city`),
  `province` = VALUES(`province`),
  `postalCode` = VALUES(`postalCode`),
  `schoolOrigin` = VALUES(`schoolOrigin`),
  `graduationYear` = VALUES(`graduationYear`),
  `entryYear` = VALUES(`entryYear`),
  `entryPath` = VALUES(`entryPath`),
  `registrationNumber` = VALUES(`registrationNumber`),
  `bloodType` = VALUES(`bloodType`),
  `jacketSize` = VALUES(`jacketSize`),
  `transportation` = VALUES(`transportation`),
  `residenceType` = VALUES(`residenceType`),
  `updatedAt` = CURRENT_TIMESTAMP(3);
